project:
  type: website

website:
  site-url: "https://mr.schochastics.net"
  title: "David Schoch - schochastics"
  favicon: "favicon.ico"
format:
  html:
    minimal: true
    css: styles.css
    toc: false
    toc-title: " "
    code-copy: false
execute: 
  echo: false
  warning: false